# Generated by Django 5.2.17 on 2026-08-27 20:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.TextField()),
                ('playlist_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=8)),
                ('preference', models.JSONField(help_text='Format spec applied to every child.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('total_items', models.IntegerField(default=0)),
                ('succeeded_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('cancelled_items', models.IntegerField(default=0)),
                ('est_total_bytes', models.BigIntegerField(default=0)),
                ('actual_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProbeCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='youtube', max_length=16)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('playlist', 'Playlist')], max_length=16)),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('channel', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('item_count', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('is_live', models.BooleanField(default=False)),
                ('payload', models.JSONField(help_text='Normalised, UI-facing probe result.')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='ix_probe_expiry')],
                'constraints': [models.UniqueConstraint(fields=('source', 'content_type', 'external_id'), name='uq_probe_identity')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_hash', models.CharField(db_index=True, max_length=32)),
                ('user_agent_hash', models.CharField(blank=True, max_length=32)),
                ('bytes_used', models.BigIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_seen_at'], name='ix_session_last_seen')],
            },
        ),
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_index', models.IntegerField(blank=True, null=True)),
                ('source_url', models.TextField(help_text='Canonicalised - never raw user input.')),
                ('video_id', models.CharField(db_index=True, max_length=32)),
                ('title', models.TextField(blank=True)),
                ('channel', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=8)),
                ('spec', models.JSONField(help_text='Container, height, bitrate, format selector, subs.')),
                ('subtitle_mode', models.CharField(choices=[('none', 'None'), ('separate', 'Separate file'), ('embed', 'Embedded')], default='none', max_length=16)),
                ('subtitle_langs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped'), ('expired', 'Expired')], default='queued', max_length=16)),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('resolving', 'Resolving'), ('downloading_video', 'Downloading video'), ('downloading_audio', 'Downloading audio'), ('downloading_subs', 'Downloading subtitles'), ('merging', 'Merging'), ('transcoding', 'Converting'), ('remuxing', 'Remuxing'), ('embedding_subs', 'Embedding subtitles'), ('embedding_meta', 'Adding metadata'), ('finalizing', 'Finalizing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('priority', models.SmallIntegerField(default=0, help_text='10 = single, 0 = batch item.')),
                ('attempts', models.SmallIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('worker_name', models.CharField(blank=True, max_length=128)),
                ('progress_percent', models.FloatField(default=0)),
                ('downloaded_bytes', models.BigIntegerField(default=0)),
                ('est_total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('output_filename', models.TextField(blank=True)),
                ('relative_path', models.TextField(blank=True, help_text='Relative to MEDIA_DONE_ROOT.')),
                ('content_type', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('error_detail', models.JSONField(blank=True, help_text='Internal only.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('not_before', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='downloads.downloadbatch')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='downloads.session')),
            ],
        ),
        migrations.AddField(
            model_name='downloadbatch',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='downloads.session'),
        ),
        migrations.CreateModel(
            name='SubtitleAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=16)),
                ('lang_name', models.CharField(blank=True, max_length=64)),
                ('is_auto', models.BooleanField(default=False)),
                ('fmt', models.CharField(max_length=8)),
                ('relative_path', models.TextField()),
                ('size_bytes', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='downloads.downloadjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(condition=models.Q(('status', 'queued')), fields=['priority', 'created_at'], name='ix_job_dispatch'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(condition=models.Q(('status__in', ['dispatched', 'running'])), fields=['session', 'status'], name='ix_job_session_active'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(condition=models.Q(('status__in', ['dispatched', 'running'])), fields=['heartbeat_at'], name='ix_job_reaper'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(condition=models.Q(('status', 'succeeded')), fields=['expires_at'], name='ix_job_expiry'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['batch', 'batch_index'], name='ix_job_batch_order'),
        ),
        migrations.AddConstraint(
            model_name='downloadjob',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False)), fields=('batch', 'batch_index'), name='uq_job_batch_index'),
        ),
        migrations.AddIndex(
            model_name='downloadbatch',
            index=models.Index(fields=['session', '-created_at'], name='ix_batch_session'),
        ),
        migrations.AddConstraint(
            model_name='subtitleasset',
            constraint=models.UniqueConstraint(fields=('job', 'lang', 'fmt', 'is_auto'), name='uq_sub_per_job'),
        ),
    ]
