# Generated by Django 5.2.17 on 2026-08-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadbatch',
            name='client_ip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='client_ip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
